### ISSUE TITLE
Installer give error..

### ISSUE THREAD

**Issue by Fronun** [zenith391/Fuchas#6] opened 2019-07-06 10:35 UTC
![Screenshot_16](https://user-images.githubusercontent.com/32768348/60755040-a3810b00-a003-11e9-9d72-7782f419d8bb.png)

**Comment by zenith391** [comment] 2019-07-08 09:33
Ok, i looked and it seems that it's caused by the installer not download the CPIO at all, gotta see why

**Comment by zenith391** [comment] 2019-07-08 15:08
Ok i found out that it was because i forgot /tmp/ was limited in size and that the 150KB CPIO was stored in it. Now the CPIO is in root (/) and deleted when extraction is complete. Now (unless you have less than 150KB free) Fuchas installation will work, so i'm closing issue

**Closed by zenith391** 2019-07-08 15:08 UTC
Labels: bug

**Comment by zenith391** [comment] 2019-07-10 13:13
Also look at Fuchas running a GUI on 1x Tier 1.5 memory
![2019-07-08_11 06 27](https://user-images.githubusercontent.com/39484230/60971775-3338f900-a325-11e9-954b-9e13bfc9bd0c.png)
